### PR TITLE
Fixing sync on local connection

### PR DESCRIPTION
**Pull request by Ricardonacif**
Makes sense? I'm getting this error:

    NameError: undefined local variable or method `sync' for #      <WebsocketRails::UserManager::LocalConnection:0x007f879790cee8>

### CODE REVIEW

**Comment by moaa** [comment]
@Ricardonacif After digging into the threadsocket-rails-sync branch that Dan published (honestly don't know what he was thinking at the time).. it seems like there's some stuff missing (and it looks like he also broke channel tokens) .. 

Can I have you try my fork under the threadsocket-rails branch?

**Comment by Ricardonacif** [comment]
Sure! I'm using Puma, will that be an issue?

**Comment by moaa** [comment]
Nope, shouldn't cause any issues.  I would suggest testing it in a non production environment first though.

**Comment by Ricardonacif** [comment]
Sure, I'm on staging right now anyway. Thanks for the help! I'll let you know during the weekend.

**Comment by Ricardonacif** [comment]
So far so good, I'll keep you posted!

**Pull request closed without merging**
